server:
   port: 8888
spring:
  datasource:
     url: jdbc:postgresql://localhost:5432/RRC_DataBase
     username: postgres
     password: admin
  jpa:
     hibernate:
        ddl-auto: update
     properties:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true

